export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_FRESH = "REGISTER_USER_FRESH"
export const UPLOAD_TOKEN = "UPLOAD_TOKEN"
export const UPLOAD_TOKEN_FRESH = "UPLOAD_TOKEN_FRESH"
export const GET_PASSWORD_RECOVER_TOKEN_BY_MAIL = "GET_PASSWORD_RECOVER_TOKEN_BY_MAIL"
export const GET_PASSWORD_RECOVER_TOKEN_BY_MAIL_FRESH = "GET_PASSWORD_RECOVER_TOKEN_BY_MAIL_FRESH"
export const GET_ALL_USERS = "GET_ALL_USERS";
export const GET_ALL_ROLES = "GET_ALL_ROLES";
export const USER_UPDATE = "USER_UPDATE";
export const USER_UPDATE_FRESH = "USER_UPDATE_FRESH";
export const USER_STATUS_UPDATE = "USER_STATUS_UPDATE"
export const USER_STATUS_UPDATE_FRESH = "USER_STATUS_UPDATE_FRESH"

