export const REGISTER_USER = "REGISTER_USER"
export const REGISTER_USER_FRESH = "REGISTER_USER_FRESH"
export const UPLOAD_TOKEN = "UPLOAD_TOKEN"
export const UPLOAD_TOKEN_FRESH = "UPLOAD_TOKEN_FRESH"
export const GET_PASSWORD_RECOVER_TOKEN_BY_MAIL =
  "GET_PASSWORD_RECOVER_TOKEN_BY_MAIL"
export const GET_PASSWORD_RECOVER_TOKEN_BY_MAIL_FRESH =
  "GET_PASSWORD_RECOVER_TOKEN_BY_MAIL_FRESH"
export const GET_ALL_USERS = "GET_ALL_USERS"
export const GET_ALL_ROLES = "GET_ALL_ROLES"
export const USER_UPDATE = "USER_UPDATE"
export const USER_UPDATE_FRESH = "USER_UPDATE_FRESH"
export const USER_STATUS_UPDATE = "USER_STATUS_UPDATE"
export const USER_STATUS_UPDATE_FRESH = "USER_STATUS_UPDATE_FRESH"
export const USER_DELETE = "USER_DELETE"
export const USER_DELETE_FRESH = "USER_DELETE_FRESH"

export const SERVER_SIDE_PAGINATION_USER = "SERVER_SIDE_PAGINATION_USER"
export const SERVER_SIDE_PAGINATION_USER_SEARCH =
  "SERVER_SIDE_PAGINATION_USER_SEARCH"
export const SERVER_SIDE_PAGINATION_SEARCH_USER_FRESH =
  "SERVER_SIDE_PAGINATION_SEARCH_USER_FRESH"

export const GET_USER_BY_ID = "GET_USER_BY_ID"
export const GET_USER_BY_ID_FRESH = "GET_USER_BY_ID_FRESH"

export const GET_ZONAL_ADMIN = "GET_ZONAL_ADMIN"
export const GET_ZONAL_ADMIN_FRESH = "GET_ZONAL_ADMIN_FRESH"

export const GET_BRANCH_ADMIN = "GET_BRANCH_ADMIN"
export const GET_BRANCH_ADMIN_FRESH = "GET_BRANCH_ADMIN_FRESH"

export const GET_CENTRAL_ADMIN = "GET_CENTRAL_ADMIN"
export const GET_CENTRAL_ADMIN_FRESH = "GET_CENTRAL_ADMIN_FRESH"
