export const ADD_VEHICLE_TYPE = "ADD_VEHICLE_TYPE"
export const ADD_VEHICLE_TYPE_FRESH = "ADD_VEHICLE_TYPE_FRESH"
export const GET_ALL_VEHICLE_TYPE = "GET_ALL_VEHICLE_TYPE"
export const GET_ALL_VEHICLE_TYPE_FRESH = "GET_ALL_VEHICLE_TYPE_FRESH"
export const VEHICLE_TYPE_EDIT = "VEHICLE_TYPE_EDIT"
export const VEHICLE_TYPE_EDIT_FRESH = "VEHICLE_TYPE_EDIT_FRESH"
export const EDIT_VEHICLE_TYPE_STATUS = "EDIT_VEHICLE_TYPE_STATUS"
export const EDIT_VEHICLE_TYPE_STATUS_FRESH = "EDIT_VEHICLE_TYPE_STATUS_FRESH"
export const GET_VEHICLE_TYPE_BY_ID = "GET_VEHICLE_TYPE_BY_ID"
export const VEHICLE_TYPE_DELETE = "VEHICLE_TYPE_DELETE"
export const VEHICLE_TYPE_DELETE_FRESH = "VEHICLE_TYPE_DELETE_FRESH"

export const SERVER_SIDE_PAGINATION_VEHICLE_TYPE =
  "SERVER_SIDE_PAGINATION_VEHICLE_TYPE"
export const SERVER_SIDE_PAGINATION_VEHICLE_TYPE_SEARCH =
  "SERVER_SIDE_PAGINATION_VEHICLE_TYPE_SEARCH"
export const SERVER_SIDE_PAGINATION_SEARCH_VEHICLE_TYPE_FRESH =
  "SERVER_SIDE_PAGINATION_SEARCH_VEHICLE_TYPE_FRESH"
