export const ADD_RESTAURANT = "ADD_RESTAURANT";
export const GET_ALL_RESTAURANT = "GET_ALL_RESTAURANT";
export const RESTAURANT_NAME_UPDATE = "RESTAURANT_NAME_UPDATE";
export const RESTAURANT_STATUS_UPDATE = "RESTAURANT_STATUS_UPDATE";
export const GET_ALL_CUSINE = "GET_ALL_CUSINE";
export const ADD_BRANCH = "ADD_BRANCH";
export const EDIT_BRANCH = "EDIT_BRANCH";
export const ADD_BRANCH_FRESH = "ADD_BRANCH_FRESH";
export const GET_ALL_BRANCH = "GET_ALL_BRANCH";
export const GET_ALL_ZONE = "GET_ALL_ZONE";
export const ADD_ZONE = "ADD_ZONE";
export const ADD_ZONE_FRESH = "ADD_ZONE_FRESH";
export const EDIT_ZONE = "EDIT_ZONE";
export const EDIT_ZONE_FRESH = "EDIT_ZONE_FRESH";
export const EDIT_BRANCH_FRESH = "EDIT_ZONE_FRESH";



