export const ADD_RESTAURANT = "ADD_RESTAURANT";
export const GET_ALL_RESTAURANT = "GET_ALL_RESTAURANT";
export const RESTAURANT_NAME_UPDATE = "RESTAURANT_NAME_UPDATE";
export const RESTAURANT_STATUS_UPDATE = "RESTAURANT_STATUS_UPDATE";
export const GET_ALL_CUSINE = "GET_ALL_CUSINE";
export const ADD_BRANCH = "ADD_BRANCH";
export const EDIT_BRANCH = "EDIT_BRANCH";
export const ADD_BRANCH_FRESH = "ADD_BRANCH_FRESH";
export const EDIT_BRANCH_STATUS = "EDIT_BRANCH_STATUS";
export const EDIT_BRANCH_STATUS_FRESH = "EDIT_BRANCH_STATUS_FRESH";
export const EDIT_BRANCH_POPULAR = "EDIT_BRANCH_POPULAR";
export const EDIT_BRANCH_POPULAR_FRESH = "EDIT_BRANCH_POPULAR_FRESH";
export const GET_ALL_BRANCH = "GET_ALL_BRANCH";
export const GET_ALL_ZONE = "GET_ALL_ZONE";
export const ADD_ZONE = "ADD_ZONE";
export const ADD_ZONE_FRESH = "ADD_ZONE_FRESH";
export const EDIT_ZONE = "EDIT_ZONE";
export const EDIT_ZONE_FRESH = "EDIT_ZONE_FRESH";
export const EDIT_ZONE_STATUS = "EDIT_ZONE_STATUS";
export const EDIT_ZONE_STATUS_FRESH = "EDIT_ZONE_STATUS_FRESH";
export const EDIT_BRANCH_FRESH = "EDIT_ZONE_FRESH";
export const ADD_ONS_CATEGORY = "ADD_ONS_CATEGORY";
export const ADD_ONS_CATEGORY_FRESH = "ADD_ONS_CATEGORY_FRESH";
export const GET_ADD_ONS_CATEGORY = "GET_ADD_ONS_CATEGORY";
export const ADD_CUISINE = "ADD_CUISINE";
export const GET_CUISINE = "GET_CUISINE";
export const EDIT_CUISINE = "EDIT_CUISINE";
export const ADD_RESTAURANT_MENU = "ADD_RESTAURANT_MENU";
export const ADD_RESTAURANT_MENU_FRESH = "ADD_RESTAURANT_MENU_FRESH";
export const GET_RESTAURANT_MENU = "GET_RESTAURANT_MENU";



