export const ADD_RESTAURANT = "ADD_RESTAURANT"
export const GET_ALL_RESTAURANT = "GET_ALL_RESTAURANT"
export const RESTAURANT_NAME_UPDATE = "RESTAURANT_NAME_UPDATE"
export const RESTAURANT_STATUS_UPDATE = "RESTAURANT_STATUS_UPDATE"
export const DELETE_RESTAURANT = "DELETE_RESTAURANT"
export const DELETE_RESTAURANT_FRESH = "DELETE_RESTAURANT_FRESH"
export const GET_ALL_CUSINE = "GET_ALL_CUSINE"
export const ADD_BRANCH = "ADD_BRANCH"
export const EDIT_BRANCH = "EDIT_BRANCH"
export const ADD_BRANCH_FRESH = "ADD_BRANCH_FRESH"
export const EDIT_BRANCH_STATUS = "EDIT_BRANCH_STATUS"
export const EDIT_BRANCH_STATUS_FRESH = "EDIT_BRANCH_STATUS_FRESH"
export const DELETE_BRANCH = "DELETE_BRANCH"
export const DELETE_BRANCH_FRESH = "DELETE_BRANCH_FRESH"
export const EDIT_BRANCH_POPULAR = "EDIT_BRANCH_POPULAR"
export const EDIT_BRANCH_POPULAR_FRESH = "EDIT_BRANCH_POPULAR_FRESH"
export const GET_ALL_BRANCH = "GET_ALL_BRANCH"
export const GET_ALL_ZONE = "GET_ALL_ZONE"
export const ADD_ZONE = "ADD_ZONE"
export const ADD_ZONE_FRESH = "ADD_ZONE_FRESH"
export const DELETE_ZONE = "DELETE_ZONE"
export const DELETE_ZONE_FRESH = "DELETE_ZONE_FRESH"
export const EDIT_ZONE = "EDIT_ZONE"
export const EDIT_ZONE_FRESH = "EDIT_ZONE_FRESH"
export const EDIT_ZONE_STATUS = "EDIT_ZONE_STATUS"
export const EDIT_ZONE_STATUS_FRESH = "EDIT_ZONE_STATUS_FRESH"
export const EDIT_BRANCH_FRESH = "EDIT_ZONE_FRESH"
export const ADD_ONS_CATEGORY = "ADD_ONS_CATEGORY"
export const ADD_ONS_CATEGORY_FRESH = "ADD_ONS_CATEGORY_FRESH"
export const GET_ADD_ONS_CATEGORY = "GET_ADD_ONS_CATEGORY"
export const EDIT_ADD_ONS_CATEGORY = "EDIT_ADD_ONS_CATEGORY"
export const EDIT_ADD_ONS_CATEGORY_FRESH = "EDIT_ADD_ONS_CATEGORY_FRESH"
export const EDIT_ADD_ON_CATEGORY_STATUS = "EDIT_ADD_ON_CATEGORY_STATUS"
export const EDIT_ADD_ON_CATEGORY_STATUS_FRESH =
  "EDIT_ADD_ON_CATEGORY_STATUS_FRESH"
export const DELETE_ADD_ON_CATEGORY = "DELETE_ADD_ON_CATEGORY"
export const DELETE_ADD_ON_CATEGORY_FRESH = "DELETE_ADD_ON_CATEGORY_FRESH"
export const ADD_CUISINE = "ADD_CUISINE"
export const GET_CUISINE = "GET_CUISINE"
export const EDIT_CUISINE = "EDIT_CUISINE"
export const EDIT_CUISINE_STATUS = "EDIT_CUISINE_STATUS"
export const DELETE_CUISINE = "DELETE_CUISINE"
export const DELETE_CUISINE_FRESH = "DELETE_CUISINE_FRESH"
export const ADD_RESTAURANT_MENU = "ADD_RESTAURANT_MENU"
export const ADD_RESTAURANT_MENU_FRESH = "ADD_RESTAURANT_MENU_FRESH"
export const GET_RESTAURANT_MENU = "GET_RESTAURANT_MENU"
export const ADD_MENU_TIME_SLOT = "ADD_MENU_TIME_SLOT"
export const ADD_MENU_TIME_SLOT_FRESH = "ADD_MENU_TIME_SLOT_FRESH"
export const GET_ALL_MENU_TIME_SLOT = "GET_ALL_MENU_TIME_SLOT"
export const EDIT_MENU_TIME_SLOT = "EDIT_MENU_TIME_SLOT"
export const EDIT_MENU_TIME_SLOT_FRESH = "EDIT_MENU_TIME_SLOT_FRESH"
export const EDIT_MENU_TIME_SLOT_STATUS = "EDIT_MENU_TIME_SLOT_STATUS"
export const EDIT_MENU_TIME_SLOT_STATUS_FRESH =
  "EDIT_MENU_TIME_SLOT_STATUS_FRESH"
export const DELETE_MENU_TIME_SLOT = "DELETE_MENU_TIME_SLOT"
export const DELETE_MENU_TIME_SLOT_FRESH = "DELETE_MENU_TIME_SLOT_FRESH"
export const GET_CATEGORY_BY_ID = "GET_CATEGORY_BY_ID"
export const GET_CATEGORY_BY_ID_FRESH = "GET_CATEGORY_BY_ID_FRESH"

export const SERVER_SIDE_PAGINATION_ZONE = "SERVER_SIDE_PAGINATION_ZONE"
export const SERVER_SIDE_PAGINATION_ZONE_SEARCH =
  "SERVER_SIDE_PAGINATION_ZONE_SEARCH"
export const SERVER_SIDE_PAGINATION_SEARCH_ZONE_FRESH =
  "SERVER_SIDE_PAGINATION_SEARCH_ZONE_FRESH"

export const SERVER_SIDE_PAGINATION_CUISINE = "SERVER_SIDE_PAGINATION_CUISINE"
export const SERVER_SIDE_PAGINATION_CUISINE_SEARCH =
  "SERVER_SIDE_PAGINATION_CUISINE_SEARCH"
export const SERVER_SIDE_PAGINATION_SEARCH_CUISINE_FRESH =
  "SERVER_SIDE_PAGINATION_SEARCH_CUISINE_FRESH"

export const SERVER_SIDE_PAGINATION_RESTAURANT =
  "SERVER_SIDE_PAGINATION_RESTAURANT"
export const SERVER_SIDE_PAGINATION_RESTAURANT_SEARCH =
  "SERVER_SIDE_PAGINATION_RESTAURANT_SEARCH"
export const SERVER_SIDE_PAGINATION_SEARCH_RESTAURANT_FRESH =
  "SERVER_SIDE_PAGINATION_SEARCH_RESTAURANT_FRESH"

export const SERVER_SIDE_PAGINATION_BRANCH = "SERVER_SIDE_PAGINATION_BRANCH"
export const SERVER_SIDE_PAGINATION_BRANCH_SEARCH =
  "SERVER_SIDE_PAGINATION_BRANCH_SEARCH"
export const SERVER_SIDE_PAGINATION_SEARCH_BRANCH_FRESH =
  "SERVER_SIDE_PAGINATION_SEARCH_BRANCH_FRESH"
export const SERVER_SIDE_PAGINATION_MENU = "SERVER_SIDE_PAGINATION_MENU"
export const SERVER_SIDE_PAGINATION_MENU_SEARCH =
  "SERVER_SIDE_PAGINATION_MENU_SEARCH"
export const SERVER_SIDE_PAGINATION_SEARCH_MENU_FRESH =
  "SERVER_SIDE_PAGINATION_SEARCH_MENU_FRESH"

export const SERVER_SIDE_PAGINATION_ADDONS_CATEGORY =
  "SERVER_SIDE_PAGINATION_ADDONS_CATEGORY"
export const SERVER_SIDE_PAGINATION_ADDONS_CATEGORY_SEARCH =
  "SERVER_SIDE_PAGINATION_ADDONS_CATEGORY_SEARCH"
export const SERVER_SIDE_PAGINATION_SEARCH_ADDONS_CATEGORY_FRESH =
  "SERVER_SIDE_PAGINATION_SEARCH_ADDONS_CATEGORY_FRESH"

export const SERVER_SIDE_PAGINATION_MENU_TIME =
  "SERVER_SIDE_PAGINATION_MENU_TIME"
export const SERVER_SIDE_PAGINATION_MENU_TIME_SEARCH =
  "SERVER_SIDE_PAGINATION_MENU_TIME_SEARCH"
export const SERVER_SIDE_PAGINATION_SEARCH_MENU_TIME_FRESH =
  "SERVER_SIDE_PAGINATION_SEARCH_MENU_TIME_FRESH"

export const GET_ZONE_BY_ID = "GET_ZONE_BY_ID"
export const GET_ZONE_BY_ID_FRESH = "GET_ZONE_BY_ID_FRESH"
