export const ADD_DINE_IN_CARD = "ADD_DINE_IN_CARD"
export const ADD_DINE_IN_CARD_FRESH = "ADD_DINE_IN_CARD_FRESH"
export const GET_ALL_DINE_IN_CARD = "GET_ALL_DINE_IN_CARD"
export const GET_ALL_DINE_IN_CARD_FRESH = "GET_ALL_DINE_IN_CARD_FRESH"
export const DINE_IN_CARD_EDIT = "DINE_IN_CARD_EDIT"
export const DINE_IN_CARD_EDIT_FRESH = "DINE_IN_CARD_EDIT_FRESH"
export const DINE_IN_CARD_STATUS_EDIT = "DINE_IN_CARD_STATUS_EDIT"
export const DINE_IN_CARD_STATUS_EDIT_FRESH = "DINE_IN_CARD_STATUS_EDIT_FRESH"
export const GET_DINE_IN_CARD_BY_ID = "GET_DINE_IN_CARD_BY_ID"
export const GET_DINE_IN_CARD_BY_ID_FRESH = "GET_DINE_IN_CARD_BY_ID_FRESH"
export const DINE_IN_CARD_DELETE = "DINE_IN_CARD_DELETE"
export const DINE_IN_CARD_DELETE_FRESH = "DINE_IN_CARD_DELETE_FRESH"
export const SERVER_SIDE_PAGINATION_DINE_IN_CARD =
  "SERVER_SIDE_PAGINATION_DINE_IN_CARD"
export const SERVER_SIDE_PAGINATION_DINE_IN_CARD_SEARCH =
  "SERVER_SIDE_PAGINATION_DINE_IN_CARD_SEARCH"
export const SERVER_SIDE_PAGINATION_SEARCH_DINE_IN_CARD_FRESH =
  "SERVER_SIDE_PAGINATION_SEARCH_DINE_IN_CARD_FRESH"
