export const ADD_VOUCHER_REQUEST = "ADD_VOUCHER_REQUEST"
export const ADD_VOUCHER_REQUEST_FRESH = "ADD_VOUCHER_REQUEST_FRESH"
export const GET_ALL_VOUCHER_REQUEST = "GET_ALL_VOUCHER_REQUEST"
export const GET_ALL_VOUCHER_REQUEST_FRESH = "GET_ALL_VOUCHER_REQUEST_FRESH"
export const VOUCHER_REQUEST_EDIT = "VOUCHER_REQUEST_EDIT"
export const VOUCHER_REQUEST_STATUS_EDIT = "VOUCHER_REQUEST_STATUS_EDIT"
export const VOUCHER_REQUEST_STATUS_EDIT_FRESH =
  "VOUCHER_REQUEST_STATUS_EDIT_FRESH"
export const VOUCHER_REQUEST_EDIT_FRESH = "VOUCHER_REQUEST_EDIT_FRESH"
export const GET_VOUCHER_REQUEST_BY_ID = "GET_VOUCHER_REQUEST_BY_ID"
export const VOUCHER_REQUEST_DELETE = "VOUCHER_REQUEST_DELETE"
export const VOUCHER_REQUEST_DELETE_FRESH = "VOUCHER_REQUEST_DELETE_FRESH"
export const SERVER_SIDE_PAGINATION_VOUCHER_REQUEST =
  "SERVER_SIDE_PAGINATION_VOUCHER_REQUEST"
export const SERVER_SIDE_PAGINATION_VOUCHER_REQUEST_FRESH =
  "SERVER_SIDE_PAGINATION_VOUCHER_REQUEST_FRESH"
