export const SERVER_SIDE_PAGINATION_BRANCH = "SERVER_SIDE_PAGINATION_BRANCH"
export const SERVER_SIDE_PAGINATION_BRANCH_FRESH =
  "SERVER_SIDE_PAGINATION_BRANCH_FRESH"
export const GET_BRANCH_BY_ID = "GET_BRANCH_BY_ID"
export const GET_BRANCH_BY_ID_FRESH = "GET_BRANCH_BY_ID_FRESH"
