export const SERVER_SIDE_PAGINATION_BRANCH = "SERVER_SIDE_PAGINATION_BRANCH"
export const SERVER_SIDE_PAGINATION_BRANCH_FRESH =
  "SERVER_SIDE_PAGINATION_BRANCH_FRESH"
export const GET_BRANCH_BY_ID = "GET_BRANCH_BY_ID"
export const GET_BRANCH_BY_ID_FRESH = "GET_BRANCH_BY_ID_FRESH"
export const GET_SORTABLE_POPULAR_BRANCH_BY_ZONE_ID =
  "GET_SORTABLE_POPULAR_BRANCH_BY_ZONE_ID"
export const GET_SORTABLE_POPULAR_BRANCH_BY_ZONE_ID_FRESH =
  "GET_SORTABLE_POPULAR_BRANCH_BY_ZONE_ID_FRESH"

export const UPDATE_SORTABLE_POPULAR_BRANCH = "UPDATE_SORTABLE_POPULAR_BRANCH"
export const UPDATE_SORTABLE_POPULAR_BRANCH_FRESH =
  "UPDATE_SORTABLE_POPULAR_BRANCH_FRESH"
