export const ADD_BRANCH_ATTRIBUTE = "ADD_BRANCH_ATTRIBUTE"
export const ADD_BRANCH_ATTRIBUTE_FRESH = "ADD_BRANCH_ATTRIBUTE_FRESH"
export const GET_ALL_BRANCH_ATTRIBUTE = "GET_ALL_BRANCH_ATTRIBUTE"
export const GET_ALL_BRANCH_ATTRIBUTE_FRESH = "GET_ALL_BRANCH_ATTRIBUTE_FRESH"
export const BRANCH_ATTRIBUTE_EDIT = "BRANCH_ATTRIBUTE_EDIT"
export const BRANCH_ATTRIBUTE_STATUS_EDIT = "BRANCH_ATTRIBUTE_STATUS_EDIT"
export const BRANCH_ATTRIBUTE_STATUS_EDIT_FRESH =
  "BRANCH_ATTRIBUTE_STATUS_EDIT_FRESH"
export const BRANCH_ATTRIBUTE_EDIT_FRESH = "BRANCH_ATTRIBUTE_EDIT_FRESH"
export const GET_BRANCH_ATTRIBUTE_BY_ID = "GET_BRANCH_ATTRIBUTE_BY_ID"
export const BRANCH_ATTRIBUTE_DELETE = "BRANCH_ATTRIBUTE_DELETE"
export const BRANCH_ATTRIBUTE_DELETE_FRESH = "BRANCH_ATTRIBUTE_DELETE_FRESH"

export const SERVER_SIDE_PAGINATION_BRANCH_ATTRIBUTE =
  "SERVER_SIDE_PAGINATION_BRANCH_ATTRIBUTE"
export const SERVER_SIDE_PAGINATION_BRANCH_ATTRIBUTE_SEARCH =
  "SERVER_SIDE_PAGINATION_BRANCH_ATTRIBUTE_SEARCH"
export const SERVER_SIDE_PAGINATION_SEARCH_BRANCH_ATTRIBUTE_FRESH =
  "SERVER_SIDE_PAGINATION_SEARCH_BRANCH_ATTRIBUTE_FRESH"
