export const ADD_POPUP = "ADD_POPUP"
export const ADD_POPUP_FRESH = "ADD_POPUP_FRESH"
export const GET_ALL_POPUP = "GET_ALL_POPUP"
export const GET_ALL_POPUP_FRESH = "GET_ALL_POPUP_FRESH"
export const POPUP_EDIT = "POPUP_EDIT"
export const POPUP_STATUS_EDIT = "POPUP_STATUS_EDIT"
export const POPUP_STATUS_EDIT_FRESH = "POPUP_STATUS_EDIT_FRESH"
export const POPUP_EDIT_FRESH = "POPUP_EDIT_FRESH"
export const GET_POPUP_BY_ID = "GET_POPUP_BY_ID"
export const GET_POPUP_BY_ID_FRESH = "GET_POPUP_BY_ID_FRESH"
export const POPUP_DELETE = "POPUP_DELETE"
export const POPUP_DELETE_FRESH = "POPUP_DELETE_FRESH"

export const SERVER_SIDE_PAGINATION_POPUP = "SERVER_SIDE_PAGINATION_POPUP"
export const SERVER_SIDE_PAGINATION_POPUP_SEARCH =
  "SERVER_SIDE_PAGINATION_POPUP_SEARCH"
export const SERVER_SIDE_PAGINATION_SEARCH_POPUP_FRESH =
  "SERVER_SIDE_PAGINATION_SEARCH_POPUP_FRESH"
