export const ADD_RIDER_WALLET_DETAIL = "ADD_RIDER_WALLET_DETAIL"
export const ADD_RIDER_WALLET_DETAIL_FRESH = "ADD_RIDER_WALLET_DETAIL_FRESH"
export const GET_ALL_RIDER_WALLET_DETAIL = "GET_ALL_RIDER_WALLET_DETAIL"
export const GET_ALL_RIDER_WALLET_DETAIL_FRESH =
  "GET_ALL_RIDER_WALLET_DETAIL_FRESH"
export const RIDER_WALLET_DETAIL_EDIT = "RIDER_WALLET_DETAIL_EDIT"
export const RIDER_WALLET_DETAIL_STATUS_EDIT = "RIDER_WALLET_DETAIL_STATUS_EDIT"
export const RIDER_WALLET_DETAIL_STATUS_EDIT_FRESH =
  "RIDER_WALLET_DETAIL_STATUS_EDIT_FRESH"
export const RIDER_WALLET_DETAIL_EDIT_FRESH = "RIDER_WALLET_DETAIL_EDIT_FRESH"
export const GET_RIDER_WALLET_DETAIL_BY_ID = "GET_RIDER_WALLET_DETAIL_BY_ID"
export const RIDER_WALLET_DETAIL_DELETE = "RIDER_WALLET_DETAIL_DELETE"
export const RIDER_WALLET_DETAIL_DELETE_FRESH =
  "RIDER_WALLET_DETAIL_DELETE_FRESH"
