export const ADD_OPERATION_TIME_SLOT = "ADD_OPERATION_TIME_SLOT"
export const ADD_OPERATION_TIME_SLOT_FRESH = "ADD_OPERATION_TIME_SLOT_FRESH"
export const GET_ALL_OPERATION_TIME_SLOT = "GET_ALL_OPERATION_TIME_SLOT"
export const GET_ALL_OPERATION_TIME_SLOT_FRESH =
  "GET_ALL_OPERATION_TIME_SLOT_FRESH"
export const OPERATION_TIME_SLOT_EDIT = "OPERATION_TIME_SLOT_EDIT"
export const OPERATION_TIME_SLOT_STATUS_EDIT = "OPERATION_TIME_SLOT_STATUS_EDIT"
export const OPERATION_TIME_SLOT_STATUS_EDIT_FRESH =
  "OPERATION_TIME_SLOT_STATUS_EDIT_FRESH"
export const OPERATION_TIME_SLOT_EDIT_FRESH = "OPERATION_TIME_SLOT_EDIT_FRESH"
export const GET_OPERATION_TIME_SLOT_BY_ID = "GET_OPERATION_TIME_SLOT_BY_ID"
export const OPERATION_TIME_SLOT_DELETE = "OPERATION_TIME_SLOT_DELETE"
export const OPERATION_TIME_SLOT_DELETE_FRESH =
  "OPERATION_TIME_SLOT_DELETE_FRESH"
